In [7]:
# TUTORIAL 1 (INTRODUCTION OT NUMPY)
# Numpy stands for numerical python and
# scipy- scientific python
# fundamental python pakages used mainly for the scientific computation and programming
# scientific programming deals with the solving scintific or mathematical problems with the
# -help of computers
# scientifc languages - MATLAB FORTRAN ALGOL APL
# Basic operation are - array, matrix, linear equation,random number, integration, differential Equation, Statistics more
print("hi")

hi


In [ ]:
# TUTORIAL 2 (HOW TO INSTALL NUMPY AND SCIPY AND PANDAS)
# how to install  the numpy scipy and the matplotlib and pands
# first you have to check the pip in cmd prompt 
# if not re-install the python
# you should check the version by the  pip --version
# then write the pip install numpy, pip install scipy , pip install matplotlib ,pip install pandas
# for verify the come ide and type import numpy ,import scipy, import matpotlib ,import pandas
# you donot get any error means your work is succesfull

In [ ]:
# TUTORIAL 3 (INTRODUCTION OT NUMPY)
# NumPy:
# numpy stands for Numerical Python
# Fundamental Python Package for scientific computing 
# contain several funtion help to solve the maths Engineering , scintific equation in computer.
# HISTORY - contribution by jim huguinin, travis oliphant


In [ ]:
# TUTORIAL 4 (SIMILARITY AND DIFFERENCE BETWEEN ARRAY AND LIST)
# Similarity
# both or mutable , or  store ,or index ,slice.
# Difference
# list : array difference
# different data type : similar data type
# we can not diveid the list : here we can
# buil in : instal numpy libra
# require more memory :  less 
# slow in calculation : have some high speed in calcultion comparitivily
# every where we can use : array used in precision work

In [ ]:
# TUTORIAL 5 (DEFINITION AND TYPES OF ARRAY)
# Array : is the collection of elements of same type
# they are most commen in other lang but not in python
# one dimensional array
# two dimensional array , threen dimensional array,  n dimemsional array


In [2]:
# TUTORIAL 6 (ARRAY FUNTION)
# how to creat the array
# many funtions help to creat the array like Array(), Zero(), Ones(), Linspace(), Random(), Array
# we can also create the array by the help of list and tuple and dictionaries
import numpy as np
# help(np.array)

a = np.array([1, 2, 3, 4])
print("result one : ",a)
print()

b = np.array([[1,2], [3,4]])
print("result two : ",b)
print()

c = np.array([[1,2,3],[5,6,7]],dtype="complex")
print("two dimentional with complex data type : ",c)

# creating the array using the tuple
d = (1,2,3,4,5)
print()
print("array by the tuple",np.array(d))

result one :  [1 2 3 4]

result two :  [[1 2]
 [3 4]]

two dimentional with complex data type :  [[1.+0.j 2.+0.j 3.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]

array by the tuple [1 2 3 4 5]


In [5]:
# TUTORIAL 7 (ARRANGE FUNITON)
# `simply called array range funtion ,"creates array of evenly spaces values within inteval"
#help(np.arrange)
print("with start and stop :",np.arange(1,10))
print()

print("without start : ",np.arange(3.0))
print()

print("with step as 2",np.arange(1,10,2))
print()

print("with complex data type : ",np.arange(10,dtype="complex"))
print()

print("all the parametres ",np.arange(1, 10, 2, dtype="float"))

with start and stop : [1 2 3 4 5 6 7 8 9]

without start :  [0. 1. 2.]

with step as 2 [1 3 5 7 9]

with complex data type :  [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]

all the parametres  [1. 3. 5. 7. 9.]


In [6]:
# TUTORIAL 8 (Zeros())
# creates array filled with zeros
import numpy as np
print("for one dimension zero values : ",np.zeros(5))
print()

print(np.zeros(3,dtype="int"))
print()

print(np.zeros((3,4)))
print()

print("order change : ",np.zeros((4,5),dtype="complex",order="f"))

for one dimension zero values :  [0. 0. 0. 0. 0.]

[0 0 0]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

order change :  [[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [7]:
# TUTORIAL 9 (ones())
# similar ot zeros here we create the array of ones
import numpy as np
# print(help(np.ones))
print()
print("one dimesional array : ",np.ones(8))
print()

print("two dimensional: ",np.ones((3,4),dtype="int"))
print()






one dimesional array :  [1. 1. 1. 1. 1. 1. 1. 1.]

two dimensional:  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]



In [8]:
# TUTORIAL 10 (EMPTY()
#help to creat on uninitialized array of the values
print(np.empty((3,4),dtype="int"))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
# TUTORIAL 11 (linspace()) liner space
# lide arange() in different manner
# creates array filled evenly spaced values help to break poits
# linspce (start, stop, num=50,endpoin=True)
print(np.linspace(0,100,num=5))
print()

print("will not give the end point : ",np.linspace(0,100,num=5,endpoint=False))
print()

print("give the step:",np.linspace(0,100,num=5,endpoint=False,retstep=True))
print()

print(np.linspace(0,100,num=5,retstep=True))
print()

print("change the data type",np.linspace(0,100,num=5,dtype="complex"))

[  0.  25.  50.  75. 100.]

will not give the end point :  [ 0. 20. 40. 60. 80.]

give the step: (array([ 0., 20., 40., 60., 80.]), 20.0)

(array([  0.,  25.,  50.,  75., 100.]), 25.0)

change the data type [  0.+0.j  25.+0.j  50.+0.j  75.+0.j 100.+0.j]


In [11]:
# TUTORIAL 12 (Eye()) 
# above funtion return the k th (k means which diagnal we want) diagnal matrix
import numpy as np
#help(np.eye)
print("general",np.eye(5))
print()

print("genral row and column with int data type ",np.eye(2,4,dtype="int"))
print()

print("genral row and column with int data type  with k value",np.eye(2,4,k=2,dtype="int"))


general [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

genral row and column with int data type  [[1 0 0 0]
 [0 1 0 0]]

genral row and column with int data type  with k value [[0 0 1 0]
 [0 0 0 1]]


In [12]:
# identity funtion
print(np.identity(5,dtype=int))
print()
print(np.identity(5))
print()
print(np.identity(4,dtype=complex))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [22]:
# TUTORIAL 13 (random()) liner space
## help(np.random.rand)
print("random 3*2 matrix",np.random.rand(4,5))
print()

print("random 3*2 matrix",np.random.randn(4,5))
print()

print(np.random.randint(2,4, size=10))

print("random 3*2 matrix",np.randn(4,5))

random 3*2 matrix [[0.44761232 0.25646739 0.53641966 0.32455721 0.93716441]
 [0.30999183 0.44396044 0.0982581  0.36928907 0.00883745]
 [0.23430655 0.1222885  0.91739405 0.21300575 0.09631211]
 [0.56709946 0.07351121 0.82873271 0.55817046 0.54633957]]

random 3*2 matrix [[ 0.58677872 -0.0837412   0.04246448 -0.46880005  0.46895183]
 [ 1.07895041 -0.68159441 -2.17787468  1.73503161 -0.36958576]
 [-0.19290677 -0.54324673  0.22809631 -0.5019225  -0.00233068]
 [ 2.04702445 -0.53201609 -0.19070151  1.05851374 -0.56605588]]

[2 3 3 3 3 2 3 2 3 3]


AttributeError: module 'numpy' has no attribute 'randn'

In [23]:
# TUTORIAL 14  (attributes)
# here we discus about the  dimension , shape ,size ,dtype, itemsize ;;
# attributes of the array
# ndim use to find the dimension
a = np.array([1,2,3,4])
print("one dimensional array",a.ndim)
print()

b =np.array([[1,3,3],[1,2,4]])
print("two dimesional array",b.ndim)
print()

#shape


print("shape of the array")
print("shape of array a is : ",a.shape)
print()

print("shape of array b is : ",b.shape)

d=np.ones((2,3,4))
print(d)
print("shape of the array d is : ",np.shape(d))

# size will tell you the number of elements of the array
print("size")
print(a.size)
print()


# dtype will tell you the type of the data type
print("tell you the data type of the array: ")
print(b.dtype)
print()

# item size give  the size of the individual size fo the each item size
print("the item size will give you in terms of the bytes ")
print()
print(b.itemsize)

one dimensional array 1

two dimesional array 2

shape of the array
shape of array a is :  (4,)

shape of array b is :  (2, 3)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
shape of the array d is :  (2, 3, 4)
size
4

tell you the data type of the array: 
int32

the item size will give you in terms of the bytes 

4


In [24]:
# TUTORIAL 15 data type
a = np.zeros(5)
print(a.dtype)
b = np.zeros(6,dtype=np.int8)
print()
# astype used to change the data type
print(a.astype(int))
print("help to convert from one to another type")
print(np.float64(a))

float64

[0 0 0 0 0]
help to convert from one to another type
[0. 0. 0. 0. 0.]


In [1]:
# TUTORIAL 16 (slicing and indexing )help to create sub array from the array
# indexing help to acces the elements of the array
# accesing the elements form the one dimesional array 
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print("to access the index of 4  : ",a[3])
print("access 4 index by negative value : ",a[-2])
print()
print("two dimensional array is given by ")
print()

b = np.array([[1,2,3,4],[4,5,6,7],[13,7,8,6]])
print(b)
print("single index : ",b[0])
print("positive index : ",b[1][2])
print("negative index is : ",b[-1][-1])
print("two dimensional array is given by ")
print()

c = np.array([
    [
        [1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 8, 9, 6]
    ],
    [
        [8, 9, 10 , 11],
        [9, 10, 99, 100],
        [4, 5, 6, 7]
    ]
    
])

print(c)
print(c[0][0][0])
print(c[-1][-1][-1])

[1 2 3 4 5]
to access the index of 4  :  4
access 4 index by negative value :  4

two dimensional array is given by 

[[ 1  2  3  4]
 [ 4  5  6  7]
 [13  7  8  6]]
single index :  [1 2 3 4]
positive index :  6
negative index is :  6
two dimensional array is given by 

[[[  1   2   3   4]
  [  4   5   6   7]
  [  7   8   9   6]]

 [[  8   9  10  11]
  [  9  10  99 100]
  [  4   5   6   7]]]
1
7


In [2]:
# TUTORIAL 16 slicing operation
# used to retrive the collection of values
# syntax is given by the array_name[start:end:step], start->inclusive, starting index
# end->exclusive, ending incex step -> difference between index
print()
print("slicing in one dimensional array ")
print("the array is",a)
print("the elements within the 1 to 5",a[1:5])
print("give all the elements in the array : ",a[:])
print("give the elements in the step 2",a[1::2])
print()

print("slicing two dimensional array")
print("syntax is : array_name[start:end:step,start:end:step]")
print(b)
print(b[1:,1:2])
print(b[1:,1:])
print(b[::,::2])
print()

print("slcing the three dimensional array")
print("array_name[start:end:step, start:end:step, start:end:step")
print(c)
print(c[:,:,0:])
print(c[:, 1:, 0:4:2])


slicing in one dimensional array 
the array is [1 2 3 4 5]
the elements within the 1 to 5 [2 3 4 5]
give all the elements in the array :  [1 2 3 4 5]
give the elements in the step 2 [2 4]

slicing two dimensional array
syntax is : array_name[start:end:step,start:end:step]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [13  7  8  6]]
[[5]
 [7]]
[[5 6 7]
 [7 8 6]]
[[ 1  3]
 [ 4  6]
 [13  8]]

slcing the three dimensional array
array_name[start:end:step, start:end:step, start:end:step
[[[  1   2   3   4]
  [  4   5   6   7]
  [  7   8   9   6]]

 [[  8   9  10  11]
  [  9  10  99 100]
  [  4   5   6   7]]]
[[[  1   2   3   4]
  [  4   5   6   7]
  [  7   8   9   6]]

 [[  8   9  10  11]
  [  9  10  99 100]
  [  4   5   6   7]]]
[[[ 4  6]
  [ 7  9]]

 [[ 9 99]
  [ 4  6]]]


In [3]:
# TUTORIAL 17 advanced slicing 
# help to get the copy of the data
# type of the advanced indexing (intger indexiing ,boolean indexing)
print("integer indexing in one dimensional array :")
print(a)
a = np.arange(1,10)
print(a)
index = np.array([1,4,5])
print(a[index])
print([2,4,5])
print()

print("intger indexing in two dimensional array : ")
b = nparray([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print("boolean indexing in the operation :")
print(a[a<4])
print(b[[0,2],[2,0]])

integer indexing in one dimensional array :
[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]
[2 5 6]
[2, 4, 5]

intger indexing in two dimensional array : 


NameError: name 'nparray' is not defined

In [4]:
# airthmetic operation is numpy
# using scalars
import numpy as np
a = np.arange(1,5)
b = np.ones((2,3))
print(b)
print("scalar operation in arrays")
print(a)
print("adding scalar 2 to array a",a+2)
print("multipling scalar 2 to array a",a*2)
print("subtracting scalar 2 to array a",a-2)
print("division scalar 2 to array a",a/2)
print("power of  scalar 2 to array a",a**2)
print()
print("adding scalar 2 to array to two dimesional array b",b*2)
print()
print("operation between two arrays")
c=np.arange(2,6)
print("adition of two different one dimentional array:",a+c)
print("multiplication of two differen one dimensional array :",a*c)
print("subtracriont of two differen one dimensional array :",a-c)
print(" division of two differen one dimensional array :",a/c)
print("modulous of two differen one dimensional array :",a%c)
print("power of the  of two differen one dimensional array :",a**c)
print("subtracrion of two differen one dimensional array :",a-c)
print("\n")
print("\n")
x=np.array([[1,2],[3,4]])
y=np.array([[6,7],[8,9]])
print(x)
print(y)
print("adition of two different        two dimentional array:",       x+y)
print("\n")
print("multiplication of two differen  two dimensional array :",x*y)
print("\n")
print("subtracriont of two differen    two dimensional array :",  x-y)
print("\n")

print(" division of two differen       two dimensional array :",     x/y)
print("\n")
print("modulous of two differen        two dimensional array :",      x%y)
print("\n")
print("power of the  of two differen   two dimensional array :", x**y)
print("\n")
print("subtracrion of two differen     two dimensional array :",   x-y)
print("\n")

[[1. 1. 1.]
 [1. 1. 1.]]
scalar operation in arrays
[1 2 3 4]
adding scalar 2 to array a [3 4 5 6]
multipling scalar 2 to array a [2 4 6 8]
subtracting scalar 2 to array a [-1  0  1  2]
division scalar 2 to array a [0.5 1.  1.5 2. ]
power of  scalar 2 to array a [ 1  4  9 16]

adding scalar 2 to array to two dimesional array b [[2. 2. 2.]
 [2. 2. 2.]]

operation between two arrays
adition of two different one dimentional array: [3 5 7 9]
multiplication of two differen one dimensional array : [ 2  6 12 20]
subtracriont of two differen one dimensional array : [-1 -1 -1 -1]
 division of two differen one dimensional array : [0.5        0.66666667 0.75       0.8       ]
modulous of two differen one dimensional array : [1 2 3 4]
power of the  of two differen one dimensional array : [   1    8   81 1024]
subtracrion of two differen one dimensional array : [-1 -1 -1 -1]




[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
adition of two different        two dimentional array: [[ 7  9]
 [11 13]]


multiplication 

In [6]:
# 19 TUTORIAL (BRODCASTING)
# broadcasting will adjust the required element  in oreder to  do the operation 
# like it will strech the scalar and add with the array give the result
print("addition of the array of different size :")
a= np.ones(5,dtype=int)
print(a)
b = np.array([1,2,3,4,5])
print(b)
print(a+b)
# broadcast rules says the shape shoulb same or the one of any one

addition of the array of different size :
[1 1 1 1 1]
[1 2 3 4 5]
[2 3 4 5 6]


In [ ]:
# TUTORIAL 20 (RESHAPE ,RESIZE)
import numpy as np
print()
print("reshaping array")
print()

# using reshape funtion : give new array without chaging the data
# syntax numpy.reshape(array,shape,order)
a = np.arange(10)
print(a)
print("shape",a.shape)
b=np.reshape(a,(5,2))
print("reshape of the array is given by",b)
c=np.reshape(a,(5,2),order="f")
print(c)
print(a.reshape((2,5)))
print()
print("resize array is given ")
print(np.resize(a,(4,3)))
print(np.resize(a,(4,4)))



#help(np.reshpae)

In [1]:
# TUTORIAL 21 (flatten and ravel funtions)
print("array flatening")
#flaten by using flaten method
# syntax arrayname.flatten(oreder)
print(b)
print("flatten the array is",b.flatten())
print("flatten coloumn wise",b.flatten(order="f"))
print()

print("ravel")
#syntax is numpy.ravel(a,oreder="f")
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.ravel(a,order="f"))
b=np.array([[2,4,6],[7,433,2]])
print(b.ravel(order="c"))
print()



array flatening


NameError: name 'b' is not defined

In [7]:
# TUTORIAL 22 (transpose and swapaxes)
# trancepose funtion
# syntax numpy.transpose(array,axes=none)
array1 = np.arange(1,11).reshape(5,2)
print(array1)
print()
print("the trancpose is :",np.transpose(array1))

# transpose of 3d array
a=np.arange(1,25).reshape(2,3,4)
print("shape",np.shape(a))
print(a)
print("transpose is: ",np.transpose(a))
print("for two rows transpose is: ",np.transpose(a,(0,1,2)))
print("for three rows transpose is: ",np.transpose(a,(1,2,0)))
print("shape",np.shape(np.transpose(a)))
print()
print("gives reverse of the array",np.transpose(array1,axes=(1,0)))
print("gives the same",np.transpose(array1,axes=(0,1)))
print()
#syntax name.transpose(axie)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

the trancpose is : [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
shape (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
transpose is:  [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
for two rows transpose is:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
for three rows transpose is:  [[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]
shape (4, 3, 2)

gives reverse of the array [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
gives the same [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]



In [8]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.transpose())
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [2]:
# swap axes funtion use to interchage the array
# numpy.swaxes(array,axis)
print("the array after swap is",np.swapaxes(a,0,1))
print("the array after swap is",np.swapaxes(a,0,1))
print("array a is ",np.arange(1,25).reshape(2,3,4))
print()


NameError: name 'np' is not defined

In [3]:
#TUTORIAL (SPLITING AND JOINING ARRAY)
# concatinate help to join two array
# syntax numpy.concatenate(arrays,axis=0,out=None)
a = np.arange(1,5)
b = np.arange(6)
c = np.arange(4)
print("joined array is",np.concatenate((a,b)))

print("joining two or more array",np.concatenate((a,b,c)))
c = np.zeros(10)
print("the result is stored in c array",np.concatenate((a,b),out=c))


NameError: name 'np' is not defined

In [9]:
# joining two dimensional array
a = np.array([[1,2],[2,3]])
b = np.array([[5,6]])
print("conacatenated 2d array is",np.concatenate((a,b)))
# vstack
print("vstack")
# syntax ;numpy.vstack(tuple)
a = np.arange(6)
n = np.arange(5)
c = np.arange(5)
#print("vstack output is :",np.vstack((n,a)))
print("vstack output is",np.vstack((n,c)))
# hstack
print("hstack")
print()
print("hstack output is :",np.hstack((a,n)))

conacatenated 2d array is [[1 2]
 [2 3]
 [5 6]]
vstack
vstack output is [[0 1 2 3 4]
 [0 1 2 3 4]]
hstack

hstack output is : [0 1 2 3 4 5 0 1 2 3 4]


In [5]:
#split the array
#syntax numpy.split(array,section,axis=0)
import numpy as np
a = np.arange(1,10)
print("give 3 array",np.split(a,3))
print()
a = np.arange(0,12).reshape(6,2)
print("give 2 array",np.split(a,2))
print()
print(np.vsplit(a,2))


give 3 array [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

give 2 array [array([[0, 1],
       [2, 3],
       [4, 5]]), array([[ 6,  7],
       [ 8,  9],
       [10, 11]])]

[array([[0, 1],
       [2, 3],
       [4, 5]]), array([[ 6,  7],
       [ 8,  9],
       [10, 11]])]


In [6]:
# TOTORIAL 27 (INSERT AND DELETE THE ELEMENTS)
#INSERT help to add the elemets in the array
#syntax is numpy.insert(array,index,values,axis=None)
import numpy as np
a = np.arange(1,5)
print("array a is",a)
print("the updated array is :",np.insert(a,1,50))
print("when we insert the floating value :",np.insert(a,1,50.00))
# it will convert it into int and the insert
print("inserting the value in different places :",np.insert(a,(1,3),50))
print()
a = np.array([[1,2],[3,4]])
print(a)
print()
print("the 2d updated array is :",np.insert(a,1,230))
print("the 2d array is :",np.insert(a,1,55,axis=0))
print("the 2d array is :",np.insert(a,1,55,axis=1))
print("the 2d array is :",np.insert(a,1,[55,25],axis=0))
# print("the 2d array is :",np.insert(a,1,[25,35,55],axis=0))


array a is [1 2 3 4]
the updated array is : [ 1 50  2  3  4]
when we insert the floating value : [ 1 50  2  3  4]
inserting the value in different places : [ 1 50  2  3 50  4]

[[1 2]
 [3 4]]

the 2d updated array is : [  1 230   2   3   4]
the 2d array is : [[ 1  2]
 [55 55]
 [ 3  4]]
the 2d array is : [[ 1 55  2]
 [ 3 55  4]]
the 2d array is : [[ 1  2]
 [55 25]
 [ 3  4]]


In [2]:
# append funtion help to add the values at the end of the array
# syntax is numpy.append(array, vlues, axis=none)
import numpy as np
z = np.array([4,4,3,3])
print(z)
print("the 25 added at the end is ",np.append(z,55)
# c = np.array([[2,3],[9,8]])
#print("the 25 added in 2d array ",np.append(z,[[4,5]],axis=0))
# delet funtion help to remove the elements from theliat 
# numpy.delet(array,obj,axis=none)

SyntaxError: unexpected EOF while parsing (<ipython-input-2-e6d00f91db25>, line 10)

In [11]:
import numpy as np
z = np.array([4,4,3,3])
print(z)
print("the 25 added at the end is ",np.append(z,55))

[4 4 3 3]
the 25 added at the end is  [ 4  4  3  3 55]


In [12]:
# delete will
import numpy as np
a = np.array([[1,2,3,4]])
print("remove 2 from the a",np.delete(a,2))
print(a)

remove 2 from the a [1 2 4]
[[1 2 3 4]]


In [4]:
# TUTORIAL 25 (MATRIX I)
# rectangular arangement of data is called matrix 
# horizotal ar called rows and the vertical is called the columns
# numpy is the library used to creat the matrix
# addition of matrix
import numpy as np 
a = np.array([[1,2],[3,4]])
b = np.array([[10,20],[30,40]])
print("the addintion (a+b) is :",a+b)
# multiplication of the matrix
print("multiplication of the matrix and b is:",a.dot(b))
print("multiplication of the matrix and b is:",np.dot(a,b))
# help(np.dot)
print("trancepose of the matrix",np.transpose(a))

the addintion (a+b) is : [[11 22]
 [33 44]]
multiplication of the matrix and b is: [[ 70 100]
 [150 220]]
multiplication of the matrix and b is: [[ 70 100]
 [150 220]]
trancepose of the matrix [[1 3]
 [2 4]]


In [12]:
# TUTORIAL 26 (MATRIX class)
#syntax numpy.matrix(data,dtype=none,copy=True)
a = np.matrix("1 2 ;3 4")
print("type one",a)
b = np.matrix([[10,20],[30,40]])
print("type two",b)

print("the addintion (a+b) is :",a+b)
# multiplication of the matrix
print("type one matrix multipllication:",a*b)
print("type one matrix multipllication:",np.dot(a,b))
print("type one matrix multipllication:",a.dot(b))
# help(np.dot)
print("type one of trancepose of the matrix",a.T)
print("type two of trancepose of the matrix",np.transpose(a))

#print("type one of trancepose of the matrix",matrix.T(a))
print("to know more about the matrix")
# help(np.matrix)

type one [[1 2]
 [3 4]]
type two [[10 20]
 [30 40]]
the addintion (a+b) is : [[11 22]
 [33 44]]
type one matrix multipllication: [[ 70 100]
 [150 220]]
type one matrix multipllication: [[ 70 100]
 [150 220]]
type one matrix multipllication: [[ 70 100]
 [150 220]]
type one of trancepose of the matrix [[1 3]
 [2 4]]
type two of trancepose of the matrix [[1 3]
 [2 4]]
to know more about the matrix


In [2]:
# TUTORIAL 27 (INVERSE OF MATRIX)
# we can solve te lineat algebric equation
# here we can alsp perform the inverse ,power of matrix, and solve the liner equation and determinants
#syntax to inverse the matrix numpy.linalg.inv(matrix)
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
print("inverse of matrix",np.linalg.inv(a))
# help(np.linalg.inv())



[[1 2]
 [3 4]]
inverse of matrix [[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
# TUTORIAL 28 (power  OF MATRIX)
# matrix power funtion
# syntax numpy.linalg.matrix_power(a,n)
print("matrix a is :",a)
print("matrix of power 2 is:",np.linalg.matrix_power(a,2))
print("matrix power 3 is:",np.linalg.matrix_power(a,3))
print()
print("matrix power 0 is:",np.linalg.matrix_power(a,0))
print()
print("matrix power -2 is:",np.linalg.matrix_power(a,-2))
print()
print("the dot product of the a with a is :",np.dot(a,a))

matrix a is : [[1 2]
 [3 4]]
matrix of power 2 is: [[ 7 10]
 [15 22]]
matrix power 3 is: [[ 37  54]
 [ 81 118]]

matrix power 0 is: [[1 0]
 [0 1]]

matrix power -2 is: [[ 5.5  -2.5 ]
 [-3.75  1.75]]

the dot product of the a with a is : [[ 7 10]
 [15 22]]


In [8]:
# TUTORIAL 29 (linear equation)
# syntax : numpy.linalg.solve(a,b)
# solve the following eqjuation 3x+y=9,x+2y=8
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print("the value the x and y is given by ",np.linalg.solve(a,b))
# solve the following equation 6x+2y-5z=13, 3x+3y-2z=13, 7x+5y-3z=26
a = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
c = np.array([13,13,26])
print("the value of x and y and z is given by ",np.linalg.solve(a,c))

the value the x and y is given by  [2. 3.]
the value of x and y and z is given by  [2. 3. 1.]


In [12]:
# TUTORIAL 30  (determinant of the matrix)
# syntax numpy.linalg.det(a)
a = np.array([[1,2],[3,4]])
print(a)
d =np.linalg.det(a)
print("determinant of the matrix a is : ",d)
print(round(d))

b = np.array([[1,2,3],[3,4,5],[7,8,9]])
print(b)
d =np.linalg.det(b)
print("determinant of the matrix a is : ",d)
print(round(d))[[1 2]
 [3 4]]
determinant of the matrix a is :  -2.0000000000000004
-2.0
[[1 2 3]
 [3 4 5]
 [7 8 9]]
determinant of the matrix a is :  -1.4591502609359235e-15
-0.0


[[1 2]
 [3 4]]
determinant of the matrix a is :  -2.0000000000000004
-2.0
[[1 2 3]
 [3 4 5]
 [7 8 9]]
determinant of the matrix a is :  -1.4591502609359235e-15
-0.0


In [29]:
import numpy as np
r = 2
l = 2
matrix = np.array([])

for i in range(r):
    
    a = np.array([])    
    for j in range(l):
        val = int(input("Enter the value of items : "))
        a = np.append(a, val)
    matrix = np.append(matrix, a)
    


Enter the value of items : 1
Enter the value of items : 2
Enter the value of items : 3
Enter the value of items : 4
[1. 2. 3. 4.]


ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead